version: '3'

services:
  php:
    build: ./site
  volumes:
    - ./:/var/www/html
    - /var/log/apache2/blog2:/var/log/apache2/
  ports:
    - '8000:80'
  environment:
    - VIRTUAL_HOST=0.0.0.0
  depends_on:
    -db

  db:
    build: ./mysql